# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-02-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24, verbose_name='用户')),
                ('password', models.CharField(max_length=24, verbose_name='密码')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name'], 'verbose_name': '标签名', 'verbose_name_plural': '标签名'},
        ),
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.BigIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='文章正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_time',
            field=models.DateField(auto_now_add=True, verbose_name='博客日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='digest',
            field=models.TextField(blank=True, null=True, verbose_name='文章摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.CharField(max_length=200, verbose_name='标题图片地址'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='博客标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='view',
            field=models.BigIntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
